name: Merge Repositories

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  merge:
    name: Merge Repositories
    runs-on: ubuntu-latest

    steps:
      - name: Checkout my repo
        uses: actions/checkout@v2
        with:
          repository: MikuX-Dev/chatgpt-clone
          token: ${{ secrets.PAT_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "MikuX-Dev"
          git config user.email "abinishanth3464@gmail.com"

      - name: Add remote for second repo
        run: |
          git remote add second-repo https://github.com/xtekky/chatgpt-clone.git

      - name: Fetch changes from second repo
        run: |
          git remote update second-repo --prune

      - name: Merge second repo into my repo
        run: |
          git merge second-repo/main --allow-unrelated-histories

      - name: Push changes to my repo
        run: |
          git push origin main
